### ISSUE TITLE
Could not retrieve mirrorlist https://mirror.webtatic.com/yum/el7/x86_64/mirrorlist

### ISSUE THREAD

**Issue by haishi633** [webdevops/Dockerfile#222] opened 2018-04-11 05:58 UTC
I try to build centos7+apache+php7 image from dockerfile, but get an error below.

Could not retrieve mirrorlist https://mirror.webtatic.com/yum/el7/x86_64/mirrorlist error was
12: Timeout on https://mirror.webtatic.com/yum/el7/x86_64/mirrorlist: (28, 'Operation timed out after 30001 milliseconds with 0 out of 0 bytes received')

 One of the configured repositories failed (Unknown),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=<repoid> ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable <repoid>
        or
            subscription-manager repos --disable=<repoid>

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true

Cannot find a valid baseurl for repo: webtatic/x86_64

**Comment by PanadeEdu** [comment] 2018-06-13 18:43
Hi,
as for the investigation I tried simply creating a build of webdevops/php-apache:centos-7-php7
This was working absolutely fine using the provided commands in this repository:
make setup
make webdevops/php-apache:centos-7-php7

We just finished fixing the build mechanic, so be aware that bugs may be fixed by that.

Could you give us more input on this topic. If the issue was missunderstood, it would be awesome if you could provide us with more clear steps to reproduce the issue. 

Greetings

**Comment by hhoechtl** [comment] 2018-06-18 07:52
Couldn't reproduce either. Maybe the mirror was really down or some firewall blocked the request. Will close for now.

**Closed by hhoechtl** 2018-06-18 07:52 UTC
Labels: needs investigation
