### ISSUE TITLE
composer issue

### ISSUE THREAD

**Issue by leonidd-hyuna** [webdevops/Dockerfile#373] opened 2020-10-27 17:15 UTC
https://github.com/webdevops/Dockerfile/blob/8f981bb239945b9d73c19f482c5fa52089693494/docker/php-official/7.4/conf/provision/entrypoint.d/20-php.sh#L75

app | -> Executing /opt/docker/provision/entrypoint.d/20-php.sh
app | ln: failed to create symbolic link '/usr/local/bin/composer': File exists
app exited with code 1

**Comment by hhoechtl** [comment] 2020-10-27 17:18
Duplicate of https://github.com/webdevops/Dockerfile/issues/372

**Closed by hhoechtl** 2020-10-27 17:18 UTC

**Comment by leonidd-hyuna** [comment] 2020-10-27 17:25
got error in case  have `COPY --from=composer:1.10.16 /usr/bin/composer /usr/local/bin/composer` in Dockerfile
otherwise if remove this line (there is no composer installation at all) getting 
`/bin/sh: 1: composer: not found`

**Comment by hhoechtl** [comment] 2020-10-27 21:20
Fixed with https://github.com/webdevops/Dockerfile/commit/40305a2a77c845356cca3ab005cf2ea5abffe927 (build pending, approx 1 hour)
