### ISSUE TITLE
Xdebug breaks on access to class static property (php-dev:5.6)

### ISSUE THREAD

**Issue by kaluzki** [webdevops/Dockerfile#224] opened 2018-04-13 22:21 UTC
# similar (same?) to https://github.com/docker-library/php/issues/133

## how to reproduce

```php
<?php
/**
 * index.php
 *
 * webdevops/php-dev:5.6 => NOK
 * webdevops/php-dev:debian-8 => OK
 * webdevops/php-dev:centos-7-php56 => OK
 * webdevops/php-dev:alpine-php5 => OK
 */

/*
docker run --rm -v $(pwd):/app \
-e XDEBUG_REMOTE_HOST="172.19.0.1" \
-e XDEBUG_CONFIG="idekey=PHPSTORM" \
-e PHP_IDE_CONFIG="serverName=app" \
webdevops/php-dev:5.6 \
php /app/index.php
*/

class Foo {
    static $bar = 'bar';
    static function bar()
    {
        return self::$bar; // breakpoint
    }
}

echo Foo::bar();
```

```
PHP Fatal error:  Access to undeclared static property: Foo::$bar in /app/index.php on line 24
PHP Stack trace:
PHP   1. {main}() /app/index.php:0
PHP   2. Foo::bar() /app/index.php:28
```

**Comment by julesjcraske** [comment] 2018-04-16 13:45
I have the same problem

**Comment by PanadeEdu** [comment] 2018-06-13 18:11
Tried to reproduce the issue.
For me It was working with given Images.
We just recently fixed the build mechanic so we have new images pushed to dockerhub.
This may have caused a fix on this issue.

Can someone please confirm that it is fixed?

My output, basicly using the given php file:
`docker run --rm -v $(pwd):/app \
-e XDEBUG_REMOTE_HOST="172.19.0.1" \
-e XDEBUG_CONFIG="idekey=PHPSTORM" \
-e PHP_IDE_CONFIG="serverName=app" \
webdevops/php-dev:5.6 \
php /app/index.php`

**Comment by coding46** [comment] 2018-06-13 19:59
Works for me too:

<img width="356" alt="bildschirmfoto 2018-06-13 um 21 58 10" src="https://user-images.githubusercontent.com/1724196/41374976-f73fd9d2-6f54-11e8-9790-2ed49aaf8ef4.png">

**Comment by PanadeEdu** [comment] 2018-06-15 19:31
I was able to reproduce this issue myself. 
I can confirm that it doesnt happen with other images.
I tried some things out and searched a bit and indeed this is a known bug, very specific to this image. 

The best workaround seems to use another debugging tool or another image in this case. 
If you use any of our other images, you should be good to go. 
I put this on wont fix for now.

**Closed** 2018-06-15 19:31 UTC
Labels: bug, wontfix
